[package]
name = "pgbh-variant-caller"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlegraph = "0.5.0"
gfa = "0.8.0"
itertools = "0.10.3"
csv = "1.1.5"
